config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :users
  resources :restaurants do
    resources :menus
    resources :menu_items, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get :missing_specialty
    end
    member do
      post :edit_specialties
    end
  end

  root 'restaurants#index'

  get 'imports' => 'imports#index', as: :imports
  post 'imports/restaurants' => 'imports#restaurants', as: :import_restaurants
  post 'imports/menu' => 'imports#menu', as: :import_menu

  get 'sorts' => 'sorts#index', as: :sorts
  get 'sorts/specialty/:id' => 'sorts#show_specialty', as: :restaurant_specialty
  get 'sorts/neighborhood/:id' => 'sorts#show_neighborhood', as: :neighborhood

  get 'restaurants/:neighborhood/todas-especialidades/' => 'restaurants#sorted', as: :sorted_by_neighborhood
  get 'restaurants/todos-os-bairros/:specialty/' => 'restaurants#sorted', as: :sorted_by_specialty
  get 'restaurants/:neighborhood/:specialty/' => 'restaurants#sorted', as: :restaurants_sorted

end

app/controllers/sorts_controller.rb
class SortsController < ApplicationController
	def index
		@restaurants = Restaurant.all
		@specialties = RestaurantSpecialty.all
		@neighborhoods = Neighborhood.all
	end

	# def show_specialty
	# 	@specialty = RestaurantSpecialty.find(params[:id])
	# 	@restaurants = @specialty.restaurants
	# end

	def show_neighborhood
		@neighborhood = Neighborhood.find(params[:id])
		@restaurants = @neighborhood.restaurants
	end

	def sorted_by_specialty
		@specialty = RestaurantSpecialty.find_by(specialty_fixed: params[:specialty])
		@restaurants = @specialty.restaurants
	end

	def sorted_by_neighborhood
		@neighborhood = Neighborhood.find_by(name_fixed: params[:neighborhood])
		@restaurants = @neighborhood.restaurants
	end
end

app/helpers/sorts_helper.rb
module SortsHelper
end

app/views/sorts/_by_neighborhood.html.erb
<% @neighborhoods.each do |neighborhood| %>
	<%= link_to neighborhood.name, sorted_by_neighborhood_path(neighborhood.name_fixed) %>
<% end %>

app/views/sorts/_by_specialty.html.erb
<% @specialties.each do |specialty| %>
	<%= link_to specialty.specialty, sorted_by_specialty_path(specialty.specialty_fixed) %>
<% end %>

app/views/sorts/index.html.erb
<h1>Sort By</h1>

<h2>Specialties</h2>

<%= render 'by_specialty' %>
<br>

<h2>Neighborhood</h2>

<%= render 'by_neighborhood' %>
<br>

app/views/sorts/show_neighborhood.html.erb
show_neighborhood.html.erb

app/views/sorts/show_specialty.html.erb
<h1>Listing restaurants with specialty: <%= @specialty.specialty %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>Number</th>
      <th>Complement</th>
      <th>Email</th>
      <th>Site</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.street %></td>
        <td><%= number_with_precision(restaurant.number, precision: 0) %></td>
        <td><%= restaurant.complement %></td>
        <td><%= restaurant.public_email %></td>
        <td><%= restaurant.site %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', sorts_path %>