config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :users
  resources :restaurants do
    resources :menus
    resources :menu_items, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get :missing_specialty
    end
    member do
      post :edit_specialties
    end
  end

  root 'restaurants#index'

  get 'imports' => 'imports#index', as: :imports
  post 'imports/restaurants' => 'imports#restaurants', as: :import_restaurants
  post 'imports/menu' => 'imports#menu', as: :import_menu

  get 'sorts' => 'sorts#index', as: :sorts
  get 'sorts/specialty/:id' => 'sorts#show_specialty', as: :restaurant_specialty
  get 'sorts/neighborhood/:id' => 'sorts#show_neighborhood', as: :neighborhood

  get 'restaurants/:neighborhood/todas-especialidades/' => 'restaurants#sorted', as: :sorted_by_neighborhood
  get 'restaurants/todos-os-bairros/:specialty/' => 'restaurants#sorted', as: :sorted_by_specialty
  get 'restaurants/:neighborhood/:specialty/' => 'restaurants#sorted', as: :restaurants_sorted

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @specialties = RestaurantSpecialty.all
  end

	def menu
    restaurant = Restaurant.find(params[:restaurant_id])
    if restaurant
      menu = Import.menu(params[:menu_file])
      menu.update(restaurant: restaurant)
    end
    redirect_to imports_path, notice: "Menu successfully imported."
  end

  def restaurants
    Import.restaurant(params[:restaurant_file])
    redirect_to imports_path, notice: "Restaurants successfully imported."
  end

  private
    def get_specialties(specialty_ids_arr)
      specialties = Array.new
      specialty_ids_arr.each do |s_id|
        specialties << RestaurantSpecialty.find(s_id.to_i)
      end
      specialties
    end

    def link_specialties(restaurant, specialty_ids_arr)
      specialties = get_specialties(specialty_ids_arr)
      specialties.each do |specialty|
        RestaurantCategorization.create(restaurant: restaurant, restaurant_specialty: specialty)
      end
    end
end

app/helpers/import_helper.rb
module ImportHelper
	def restaurant_options
		select_options = @restaurants.collect{ |r| [r.name, r.id] }
	  options_for_select(select_options)
	end
end

app/helpers/imports_helper.rb
module ImportsHelper
	def restaurant_options
		select_options = @restaurants.collect{ |r| [r.name_fixed, r.id] }
	  options_for_select(select_options)
	end
end

app/views/imports/_menu.html.erb
<h2>Import Menu</h2>
<i>*Important: Select a restaurant</i>
<br><br>
<%= form_tag import_menu_path, multipart: true do %>
  <%= label_tag(:restaurant_id, "Restaurant Name: ") %>
	<%= select_tag(:restaurant_id, restaurant_options, options = { prompt: "Select a restaurant" }) %>
  <%= file_field_tag :menu_file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/imports/_restaurants.html.erb
<h2>Import Restaurants</h2>
<%= form_tag import_restaurants_path, multipart: true do %>
  <%= file_field_tag :restaurant_file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/imports/index.html.erb
<h1>Import New Restaurants and Menus</h1>
<p>Please attach spreadsheets in the correct format so it can be imported properly into the database.</p>
<%= render 'imports/restaurants' %>
<br>
<i>*Important: Restaurants are imported with no specialty selected. Please click the link below to select them.</i>
<br><br>
<%= link_to 'Restaurants with no specialties', missing_specialty_restaurants_path %>
<br>
<%= render 'imports/menu' %>
<br>
<br>
<% if flash[:notice] %>
  <div id="notice"><%= flash[:notice] %></div>
<% end %>
<br><br>