config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :users
  resources :restaurants do
    resources :menus
    resources :menu_items, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get :missing_specialty
    end
    member do
      post :edit_specialties
    end
  end

  root 'restaurants#index'

  get 'imports' => 'imports#index', as: :imports
  post 'imports/restaurants' => 'imports#restaurants', as: :import_restaurants
  post 'imports/menu' => 'imports#menu', as: :import_menu

  get 'sorts' => 'sorts#index', as: :sorts
  get 'sorts/specialty/:id' => 'sorts#show_specialty', as: :restaurant_specialty
  get 'sorts/neighborhood/:id' => 'sorts#show_neighborhood', as: :neighborhood

  get 'restaurants/:neighborhood/todas-especialidades/' => 'restaurants#sorted', as: :sorted_by_neighborhood
  get 'restaurants/todos-os-bairros/:specialty/' => 'restaurants#sorted', as: :sorted_by_specialty
  get 'restaurants/:neighborhood/:specialty/' => 'restaurants#sorted', as: :restaurants_sorted

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :restaurant_categorizations
	has_many :restaurant_specialties, through: :restaurant_categorizations
	has_many :photos, as: :imageable
	has_many :favorited_relationships
	has_many :preferred_customers, through: :favorited_relationships, source: :user
	belongs_to :neighborhood_model, class_name: "Neighborhood"
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :edit_specialties]

  #get
  def sorted
    @neighborhood = Neighborhood.find_by(name_fixed: params[:neighborhood])
    @specialty = RestaurantSpecialty.find_by(specialty_fixed: params[:specialty])
    @restaurants = filter_restaurants(@neighborhood, @specialty)
  end

  # get
  def missing_specialty
    @restaurants = Array.new
    Restaurant.all.each do |restaurant|
      @restaurants << restaurant if restaurant.restaurant_specialties.empty?
    end
  end

  # post
  def edit_specialties
    RestaurantSpecialty.all.each do |specialty|
      if params[:specialty].include? specialty.id.to_s
        RestaurantCategorization.find_or_create_by(restaurant: @restaurant, restaurant_specialty: specialty)
      else
        restaurant_categorization = RestaurantCategorization.find_by(restaurant: @restaurant, restaurant_specialty: specialty)
        if restaurant_categorization
          restaurant_categorization.destroy
        end
      end
    end
    redirect_to @restaurant, notice: 'Restaurant specialties successfully updated.'
  end

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @menu = @restaurant.menus.select { |menu| menu.status == "current" }.first
    @menu_sessions = Array.new
    @menu.items.each do |item|
      @menu_sessions << item.session unless @menu_sessions.include? item.session
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
    @menu = @restaurant.menus.select { |menu| menu.status == "current" }.first
    @specialties = @restaurant.restaurant_specialties
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)  
    if @restaurant.save

      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
    def filter_restaurants(neighborhood, specialty)
      restaurants_n = neighborhood ? neighborhood.restaurants : Restaurant.all
      restaurants_s = specialty ? specialty.restaurants : Restaurant.all
      restaurants_n & restaurants_s
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :street, :number, :complement, :neighborhood, :city, :state, :CEP, :region, :public_email, :contact_email, :phone, :site)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
	def select_session_items(session)
		@menu.items.select { |item| item.session == session }
	end

	def has_specialty?(specialty_id)
		@specialties.include? RestaurantSpecialty.find(specialty_id)
	end
end

app/views/restaurants/_edit_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :complement %><br>
    <%= f.text_field :complement %>
  </div>
  <div class="field">
    <%= f.label :neighborhood %><br>
    <%= f.text_field :neighborhood %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :CEP %><br>
    <%= f.text_field :CEP %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :public_email %><br>
    <%= f.text_field :public_email %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_edit_menu_form.erb
<h2>Edit menu</h2>

<table>
  <thead>
    <tr>
      <th>Session</th>
      <th>Product</th>
      <th>Product Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu.items.each do |item| %>
      <tr>
        <td><%= item.session %></td>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= number_with_precision(item.price, precision: 2) %></td>
        <td><%= link_to 'Edit', edit_restaurant_menu_item_path(@restaurant, item) %></td>
        <td><%= link_to 'Delete', [@restaurant, item], method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/_edit_restaurant_form.html.erb
<h2>Edit information</h2>
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :complement %><br>
    <%= f.text_field :complement %>
  </div>
  <div class="field">
    <%= f.label :neighborhood %><br>
    <%= f.text_field :neighborhood %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :CEP %><br>
    <%= f.text_field :CEP %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :public_email %><br>
    <%= f.text_field :public_email %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_edit_specialties_form.html.erb
<h2>Edit specialties</h2>
<% i = 0 %>
<%= form_tag edit_specialties_restaurant_path(@restaurant), multipart: true do %>
	<% RestaurantSpecialty.all.each do |specialty| %>
		<%= check_box_tag "specialty[]", specialty.id, has_specialty?(specialty.id) %>
		<%= label_tag "specialty[#{specialty.id}]", specialty.specialty %>
		<% i += 1 %>
		<% if i % 10 == 0 %><br><% end %>
	<% end %>
	<br><br>
	<%= submit_tag "Update Specialties" %>
<% end %>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :complement %><br>
    <%= f.text_field :complement %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing restaurant</h1>

<%= render 'edit_restaurant_form' %>
<%= render 'edit_specialties_form' %>
<%= render 'edit_menu_form' %>
<br>

<%= link_to 'New', new_restaurant_menu_item_path(@restaurant) %> |
<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>Number</th>
      <th>Complement</th>
      <th>Email</th>
      <th>Site</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.street %></td>
        <td><%= number_with_precision(restaurant.number, precision: 0) %></td>
        <td><%= restaurant.complement %></td>
        <td><%= restaurant.public_email %></td>
        <td><%= restaurant.site %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/missing_specialty.html.erb
<h1>Listing restaurants with no specialty</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>Number</th>
      <th>Complement</th>
      <th>Email</th>
      <th>Site</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.street %></td>
        <td><%= number_with_precision(restaurant.number, precision: 0) %></td>
        <td><%= restaurant.complement %></td>
        <td><%= restaurant.public_email %></td>
        <td><%= restaurant.site %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', imports_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'edit_restaurant_form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<h1 id="restaurant_name"><%= @restaurant.name %></h1>
<p><%= @restaurant.street %>, <%= @restaurant.number.to_i.to_s %><% if @restaurant.complement %> <%= @restaurant.complement %><% end %> - <%= @restaurant.city %> - <%= @restaurant.state %> - <%= @restaurant.CEP %></p>
<p id="restaurant_email"><%= @restaurant.public_email %></p>
<p id="restaurant_site"><%= @restaurant.site %></p>

<h2>Menu</h2>

<% @menu_sessions.each do |session| %>
	<div class="menu_session">
		<h3 id="menu_session_title"><%= session %></h3>
		<% session_items = select_session_items(session) %>
		<% session_items.each do |item| %>
			<strong><%= item.name %></strong><br>
			<em><%= item.description %></em><br>
			<u><%= number_with_precision(item.price, precision: 2) %></u><br><br>
		<% end %>
	</div>
<% end %>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/sorted.html.erb
<h1>Listing restaurants with filters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>Number</th>
      <th>Complement</th>
      <th>Email</th>
      <th>Site</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.street %></td>
        <td><%= number_with_precision(restaurant.number, precision: 0) %></td>
        <td><%= restaurant.complement %></td>
        <td><%= restaurant.public_email %></td>
        <td><%= restaurant.site %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', sorts_path %>